
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALEATORIO BINARIO FIN_ENTRADA HEXADECIMAL NUMERO_DECIMAL OCTAL PALABRA ROMANO \n    Simbolo_inicial : NUMERO_DECIMAL ROMANO FIN_ENTRADA\n                    | NUMERO_DECIMAL BINARIO FIN_ENTRADA\n                    | NUMERO_DECIMAL OCTAL FIN_ENTRADA\n                    | NUMERO_DECIMAL HEXADECIMAL FIN_ENTRADA\n                    | NUMERO_DECIMAL PALABRA FIN_ENTRADA\n                    | NUMERO_DECIMAL ALEATORIO FIN_ENTRADA\n    '
    
_lr_action_items = {'NUMERO_DECIMAL':([0,],[2,]),'$end':([1,9,10,11,12,13,14,],[0,-1,-2,-3,-4,-5,-6,]),'ROMANO':([2,],[3,]),'BINARIO':([2,],[4,]),'OCTAL':([2,],[5,]),'HEXADECIMAL':([2,],[6,]),'PALABRA':([2,],[7,]),'ALEATORIO':([2,],[8,]),'FIN_ENTRADA':([3,4,5,6,7,8,],[9,10,11,12,13,14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Simbolo_inicial':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Simbolo_inicial","S'",1,None,None,None),
  ('Simbolo_inicial -> NUMERO_DECIMAL ROMANO FIN_ENTRADA','Simbolo_inicial',3,'p_gramatica','Coversor.py',85),
  ('Simbolo_inicial -> NUMERO_DECIMAL BINARIO FIN_ENTRADA','Simbolo_inicial',3,'p_gramatica','Coversor.py',86),
  ('Simbolo_inicial -> NUMERO_DECIMAL OCTAL FIN_ENTRADA','Simbolo_inicial',3,'p_gramatica','Coversor.py',87),
  ('Simbolo_inicial -> NUMERO_DECIMAL HEXADECIMAL FIN_ENTRADA','Simbolo_inicial',3,'p_gramatica','Coversor.py',88),
  ('Simbolo_inicial -> NUMERO_DECIMAL PALABRA FIN_ENTRADA','Simbolo_inicial',3,'p_gramatica','Coversor.py',89),
  ('Simbolo_inicial -> NUMERO_DECIMAL ALEATORIO FIN_ENTRADA','Simbolo_inicial',3,'p_gramatica','Coversor.py',90),
]
